
server:
  port: 8080

spring:
  profiles: 
    active: "dev"
# Mongo DB Configuration
  data:
    mongodb:
      # host: 192.168.178.60
      host: 192.168.3.158
      database: "mockora"
      port: 27017
