
logging:
  level:
    org.springframework: ERROR
    co.lps.mockora: DEBUG

spring:
  profiles: dev
  url: http://localhost

  data:
    mongodb:
      host: localhost
      port: 27017
      database: mockora
      username: mongodb
      password: mongodb#1



